//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int MainWindowSplitContainerDistance {
            get {
                return ((int)(this["MainWindowSplitContainerDistance"]));
            }
            set {
                this["MainWindowSplitContainerDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MainWindowLeft {
            get {
                return ((int)(this["MainWindowLeft"]));
            }
            set {
                this["MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MainWindowTop {
            get {
                return ((int)(this["MainWindowTop"]));
            }
            set {
                this["MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int MainWindowWidth {
            get {
                return ((int)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("599")]
        public int MainWindowHeight {
            get {
                return ((int)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowState {
            get {
                return ((int)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxFirstVisibleCharIndex1 {
            get {
                return ((int)(this["BookmarksRichTextBoxFirstVisibleCharIndex1"]));
            }
            set {
                this["BookmarksRichTextBoxFirstVisibleCharIndex1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxFirstVisibleCharIndex2 {
            get {
                return ((int)(this["BookmarksRichTextBoxFirstVisibleCharIndex2"]));
            }
            set {
                this["BookmarksRichTextBoxFirstVisibleCharIndex2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxFirstVisibleCharIndex3 {
            get {
                return ((int)(this["BookmarksRichTextBoxFirstVisibleCharIndex3"]));
            }
            set {
                this["BookmarksRichTextBoxFirstVisibleCharIndex3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxFirstVisibleCharIndex4 {
            get {
                return ((int)(this["BookmarksRichTextBoxFirstVisibleCharIndex4"]));
            }
            set {
                this["BookmarksRichTextBoxFirstVisibleCharIndex4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxFirstVisibleCharIndex5 {
            get {
                return ((int)(this["BookmarksRichTextBoxFirstVisibleCharIndex5"]));
            }
            set {
                this["BookmarksRichTextBoxFirstVisibleCharIndex5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxFirstVisibleCharIndex6 {
            get {
                return ((int)(this["BookmarksRichTextBoxFirstVisibleCharIndex6"]));
            }
            set {
                this["BookmarksRichTextBoxFirstVisibleCharIndex6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxFirstVisibleCharIndex7 {
            get {
                return ((int)(this["BookmarksRichTextBoxFirstVisibleCharIndex7"]));
            }
            set {
                this["BookmarksRichTextBoxFirstVisibleCharIndex7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxFirstVisibleCharIndex8 {
            get {
                return ((int)(this["BookmarksRichTextBoxFirstVisibleCharIndex8"]));
            }
            set {
                this["BookmarksRichTextBoxFirstVisibleCharIndex8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxFirstVisibleCharIndex9 {
            get {
                return ((int)(this["BookmarksRichTextBoxFirstVisibleCharIndex9"]));
            }
            set {
                this["BookmarksRichTextBoxFirstVisibleCharIndex9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxSelectionStart1 {
            get {
                return ((int)(this["BookmarksRichTextBoxSelectionStart1"]));
            }
            set {
                this["BookmarksRichTextBoxSelectionStart1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxSelectionStart2 {
            get {
                return ((int)(this["BookmarksRichTextBoxSelectionStart2"]));
            }
            set {
                this["BookmarksRichTextBoxSelectionStart2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxSelectionStart3 {
            get {
                return ((int)(this["BookmarksRichTextBoxSelectionStart3"]));
            }
            set {
                this["BookmarksRichTextBoxSelectionStart3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxSelectionStart4 {
            get {
                return ((int)(this["BookmarksRichTextBoxSelectionStart4"]));
            }
            set {
                this["BookmarksRichTextBoxSelectionStart4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxSelectionStart5 {
            get {
                return ((int)(this["BookmarksRichTextBoxSelectionStart5"]));
            }
            set {
                this["BookmarksRichTextBoxSelectionStart5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxSelectionStart6 {
            get {
                return ((int)(this["BookmarksRichTextBoxSelectionStart6"]));
            }
            set {
                this["BookmarksRichTextBoxSelectionStart6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxSelectionStart7 {
            get {
                return ((int)(this["BookmarksRichTextBoxSelectionStart7"]));
            }
            set {
                this["BookmarksRichTextBoxSelectionStart7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxSelectionStart8 {
            get {
                return ((int)(this["BookmarksRichTextBoxSelectionStart8"]));
            }
            set {
                this["BookmarksRichTextBoxSelectionStart8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BookmarksRichTextBoxSelectionStart9 {
            get {
                return ((int)(this["BookmarksRichTextBoxSelectionStart9"]));
            }
            set {
                this["BookmarksRichTextBoxSelectionStart9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksTreeNodeName1 {
            get {
                return ((string)(this["BookmarksTreeNodeName1"]));
            }
            set {
                this["BookmarksTreeNodeName1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksTreeNodeName2 {
            get {
                return ((string)(this["BookmarksTreeNodeName2"]));
            }
            set {
                this["BookmarksTreeNodeName2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksTreeNodeName3 {
            get {
                return ((string)(this["BookmarksTreeNodeName3"]));
            }
            set {
                this["BookmarksTreeNodeName3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksTreeNodeName4 {
            get {
                return ((string)(this["BookmarksTreeNodeName4"]));
            }
            set {
                this["BookmarksTreeNodeName4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksTreeNodeName5 {
            get {
                return ((string)(this["BookmarksTreeNodeName5"]));
            }
            set {
                this["BookmarksTreeNodeName5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksTreeNodeName6 {
            get {
                return ((string)(this["BookmarksTreeNodeName6"]));
            }
            set {
                this["BookmarksTreeNodeName6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksTreeNodeName7 {
            get {
                return ((string)(this["BookmarksTreeNodeName7"]));
            }
            set {
                this["BookmarksTreeNodeName7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksTreeNodeName8 {
            get {
                return ((string)(this["BookmarksTreeNodeName8"]));
            }
            set {
                this["BookmarksTreeNodeName8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksTreeNodeName9 {
            get {
                return ((string)(this["BookmarksTreeNodeName9"]));
            }
            set {
                this["BookmarksTreeNodeName9"] = value;
            }
        }
    }
}
